name: Java CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'adopt'
      - name: Build dbgate with Ant
        run: |
          cd dbgate
          ant -noinput -buildfile build.xml
      - name: Build dbgatetestapp with Ant
        run: |
          cd dbgatetestapp
          ant -noinput -buildfile build.xml
      - name: Build performancetest with Ant
        run: |
          cd performancetest
          ant -noinput -buildfile build.xml
      - name: Test Report
        uses: dorny/test-reporter@v1
        if: success() || failure()   
        with:
          name: JUnit Tests           
          path: dbgate/ci/reports/*.xml   
          reporter: jest-junit  