name: Build and Test
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'adopt'
      - name: Build dbgate
        run: |
          cd dbgate
          ant -noinput -buildfile build.xml
      - name: Build dbgatetestapp
        run: |
          cd dbgatetestapp
          ant -noinput -buildfile build.xml
      - name: Build performancetest
        run: |
          cd performancetest
          ant -noinput -buildfile build.xml
      - name: Generate test report
        uses: dorny/test-reporter@v1
        if: success() || failure()   
        with:
          name: JUnit Tests           
          path: dbgate/ci/reports/*.xml   
          reporter: java-junit  
      - name: Publish packages
        uses: actions/upload-artifact@v4
        with:
          name: package
          path: dbgate/ci/jar
      - name: Publish code coverage
        uses: actions/upload-artifact@v4
        with:
          name: code-coverage
          path: dbgate/ci/coverage
